# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib RcppXLSXwriter
#' @export
#' @import Rcpp methods
helloworld <- function(file_, M, t) {
    invisible(.Call('RcppXLSXwriter_helloworld', PACKAGE = 'RcppXLSXwriter', file_, M, t))
}

