# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib libxlsxwriter
#' @export
#' @import Rcpp methods
helloworld <- function(file_, M, t) {
    invisible(.Call('libxlsxwriter_helloworld', PACKAGE = 'libxlsxwriter', file_, M, t))
}

